import json
import re
import time
from groq import Groq, RateLimitError

from app.config import get_settings
from app.orchestrator.system_prompt import build_system_prompt
from app.orchestrator.tools import TOOL_SCHEMAS, execute_tool

_settings = get_settings()
_client = Groq(api_key=_settings.groq_api_key)

MAX_TOOL_ITERATIONS = 5
_MAX_RETRIES = 1
# No artificial history cap — the model's 32k context window is the real limit.
_MAX_HISTORY_TURNS = None

# Matches any [Memory: ...] prefix the model may generate by mimicking history.
_MEMORY_TAG_RE = re.compile(r'^\[Memory:[^\]]*\]\s*', re.IGNORECASE)


def _chat_with_retry(messages: list[dict]) -> object:
    for attempt in range(_MAX_RETRIES + 1):
        try:
            return _client.chat.completions.create(
                model=_settings.groq_model,
                messages=messages,
                tools=TOOL_SCHEMAS,
                tool_choice="auto",
            )
        except RateLimitError as exc:
            if attempt == _MAX_RETRIES:
                raise
            retry_after = 10
            if hasattr(exc, "response") and exc.response is not None:
                retry_after = int(exc.response.headers.get("retry-after", 10))
            retry_after = min(retry_after, 15)
            time.sleep(retry_after)
    raise RuntimeError("Unreachable")


def _clean(text: str) -> str:
    """Strip any [Memory: ...] prefix the model generated by mimicking its own history."""
    return _MEMORY_TAG_RE.sub("", text).strip()


def run_turn(
    user_message: str,
    financial_profile: dict,
    messages: list[dict],
) -> tuple[str, dict, list[dict]]:
    system_prompt = build_system_prompt(json.dumps(financial_profile, indent=2))

    trimmed_messages = (
        messages[-(2 * _MAX_HISTORY_TURNS):]
        if _MAX_HISTORY_TURNS and len(messages) > 2 * _MAX_HISTORY_TURNS
        else messages
    )

    context: list[dict] = list(trimmed_messages) + [{"role": "user", "content": user_message}]

    # Save any text the model produces even when it also makes tool calls —
    # used as fallback if the loop exhausts before a clean text-only response.
    last_text: str | None = None

    for iteration in range(MAX_TOOL_ITERATIONS):
        response = _chat_with_retry(
            [{"role": "system", "content": system_prompt}] + context,
        )

        message = response.choices[0].message

        if message.content and message.content.strip():
            last_text = _clean(message.content)

        if not message.tool_calls:
            assistant_text = last_text or ""
            updated_messages = list(messages) + [
                {"role": "user", "content": user_message},
                {"role": "assistant", "content": assistant_text},
            ]
            return assistant_text, financial_profile, updated_messages

        context.append({
            "role": "assistant",
            "content": message.content,
            "tool_calls": [
                {
                    "id": tc.id,
                    "type": "function",
                    "function": {
                        "name": tc.function.name,
                        "arguments": tc.function.arguments,
                    },
                }
                for tc in message.tool_calls
            ],
        })

        for tc in message.tool_calls:
            args = json.loads(tc.function.arguments)
            result, financial_profile = execute_tool(tc.function.name, args, financial_profile)
            context.append({
                "role": "tool",
                "tool_call_id": tc.id,
                "content": json.dumps(result),
            })

    fallback_text = last_text or "I'm having trouble processing that. Could you repeat your question?"
    updated_messages = list(messages) + [
        {"role": "user", "content": user_message},
        {"role": "assistant", "content": fallback_text},
    ]
    return fallback_text, financial_profile, updated_messages
